#!/usr/bin/env bash
# shellcheck disable=SC2139 # expands when defined, not when used

alias c.='code .'
alias code.='code .'
alias code-bash='code '"${BASH_PROFILE_DIR}"
alias code-settings='cat '"${USER_HOME}"'/AppData/Roaming/Code/User/settings.json'
