#!/usr/bin/env bash
alias gs='git status'

alias git-amend='git add . && git commit --amend'
alias git-amend-push='git-amend && git push -f'
alias git-message='echo "Changes in $(git rev-parse --abbrev-ref HEAD) on $(date +%Y-%m-%d) at $(date +%H:%M:%S)"'
alias git-commit='git commit -am "$(git-message)"'
alias git-commit-push='git-commit; git push'
alias git-nossl='git config --global http.sslVerify false'
alias git-ssl='git config --global http.sslVerify true'
alias git-unset-password='git config --global --unset user.password'

# Pull from multiple git remote repositories (can also be nested).
function git_pull() {
  local dir git_dir remote

  for dir in "${@:-.}"; do
    find "${dir}" -type d -name '.git' | while read -r git_dir; do
      (
        if cd "${git_dir}/.."; then
          git remote | while IFS= read -r remote; do
            echo ""
            echo "Pulling from $(git remote get-url "${remote}") (${remote}) to $(pwd)"
            git pull --tags --force "${remote}"
          done
        fi
      )
    done
  done
}
alias git-pull=git_pull

# Redo all changes from the current branch to a new branch based on another branch.
function git_redo() {
  local new_branch=${1:?new branch} new_from=${2:-develop} origin=${3:-origin}
  local current_branch
  current_branch=$(git rev-parse --abbrev-ref HEAD)
  git checkout "${new_from}" || return 1
  git pull --tags --force "${origin}" "${new_from}" || return 1
  git checkout -b "${new_branch}" || return 1
  git merge --squash --no-commit "${current_branch}" || return 1
  git status
}
alias git-redo=git_redo
