#!/usr/bin/env bash
alias gs='git status'

alias git-amend='git add . && git commit --amend'
alias git-amend-push='git-amend && git push -f'
alias git-commit='git commit -am "Message $(head -1 <(fold -w 20  <(tr -dc "a-zA-Z0-9" < /dev/urandom)))"'
alias git-commit-push='git-commit; git push'

# Pull from multiple git remote repositories (can also be nested).
function git_pull() {
  local dir git_dir remote

  for dir in "${@:-.}"; do
    find "${dir}" -type d -name '.git' | while read -r git_dir; do
      (
        if cd "${git_dir}/.."; then
          git remote | while IFS= read -r remote; do
            echo ""
            echo "Pulling from $(git remote get-url "${remote}") (${remote}) to $(pwd)"
            git pull --tags --force "${remote}"
          done
        fi
      )
    done
  done
}
alias git-pull=git_pull
