#!/usr/bin/env bash
# shellcheck disable=SC2139

alias g2='cd '"${USER_HOME}"'/.gradle/caches/modules-2/files-2.1'
alias g2-clear='rm -r '"${USER_HOME}"'/.gradle/caches/'

alias g='./gradlew'
alias g-build='g clean build -x test'
alias g-tree='(g dependencies | tee .tree)'

