#!/usr/bin/env bash

if [[ -z ${JAVA_HOME} ]]; then
  JAVA_HOME=$(which java 2> /dev/null)\
    && JAVA_HOME=$(readlink -e "${JAVA_HOME}")\
    && JAVA_HOME=${JAVA_HOME%%/bin/java}\
    && export JAVA_HOME
fi
