#!/usr/bin/env bash
# shellcheck disable=SC2139

alias m2='cd '"${USER_HOME}"'/.m2/repository'
alias m2-clear='find '"${USER_HOME}"'/.m2/repository -name '\''*.lastUpdated'\'' -delete'

alias mvn-tree='mvn -Dstyle.color=never dependency:tree | tee .tree'
alias mvn-install='mvn clean install -DskipTests=true'
alias mvn-settings='mvn help:effective-settings'
alias mvn-sources='mvn dependency:resolve -Dclassifier=sources'
alias mvn-javadoc='mvn dependency:resolve -Dclassifier=javadoc'
