#!/usr/bin/env bash
# shellcheck disable=SC2139

# Print ${PATH} in user friendly maner
alias PATH='(echo "${PATH}" | tr ":" "\n")'

alias l='ls -lha'
alias env='env | sort'
alias cls=clear

# Find all declared variables with names starting with ...
alias declared='declare -p | grep '

# Find all files except the contents of system folders
alias find-f='find . -type f -not -path "./.*/*" | sort'

# Trim spaces, new lines, comments, empty lines, etc.
alias trim-space='sed -e '\''s/^[ \t]*//; s/[ \t]*$//;'\'''
alias trim-nl='tr -d '\''\n'\'''
alias trim-comments='sed '\''/^#.*$/d'\'''
alias trim-empty='sed '\''/^$/d'\'''

alias cd-bash='cd '"${BASH_PROFILE_DIR}"

alias encode-secret="${BASH_PROFILE_DIR}"'/sh/secret.sh'
alias decode-secret="${BASH_PROFILE_DIR}"'/sh/secret.sh -d'
