#!/usr/bin/env bash

alias l='ls -lha'
alias env='env | sort'
alias cls=clear
alias find-all='find | grep -v -e ^\./\.git'

# Trim spaces, new lines, comments, empty lines, etc.
alias trim-space='sed -e '\''s/^[ \t]*//; s/[ \t]*$//;'\'''
alias trim-nl='tr -d '\''\n'\'''
alias trim-comments='sed '\''/^#.*$/d'\'''
alias trim-empty='sed '\''/^$/d'\'''

alias jar-info-all='jar-info *.jar'

alias gs='git status'
alias git-url='cat .git/config | grep url | sed "s/.*url = //"'
alias git-commit='git commit -m "Message $(head -1 <(fold -w 20  <(tr -dc "a-zA-Z0-9" < /dev/urandom)))"'
alias git-amend='git add . && git commit --amend && git push -f'

alias code.='code'
alias code-bash='code ~/.bash'

alias d='docker'
alias d-run='docker run -it --rm'
alias d-bash='docker run -it --rm --entrypoint //bin/bash'
alias d-exec='docker exec -it'
alias d-images='docker images --format="{{.Repository}}:{{.Tag}} {{.Size}} ({{.ID}})" | sort'
alias d-stats='(docker ps -q | xargs docker stats --no-stream)'
alias d-stop='docker container stop "$(docker container ls -q)"'
alias d-prune='(docker system prune -f; docker volume prune -f)'
alias compose='docker compose'
