#!/usr/bin/env bash
# shellcheck disable=SC2139 # expands when defined, not when used

# Print ${PATH} in user friendly maner
alias PATH='(echo "${PATH}" | tr ":" "\n")'

alias cd-bash='cd '"${BASH_PROFILE_DIR}"
alias 'cd..'='cd ..'
alias 'cd...'='cd ../..'
alias '..'='cd ..'
alias '...'='cd ../..'
alias '....'='cd ../../..'
alias l='ls -lha'
alias env='env | sort'
alias cls=clear

# Find all declared variables with names starting with ...
alias declared='declare -p | grep '

# Find all files except the contents of system folders
function find_f() {
  find "${1:-.}" -type f -not -path './.*/*' | sort
}
alias find-f=find_f

# Show a tree-like layout of files except from the contents of system folders
function find_tree() {
  find "${1:-.}" -not -path './.*/*'\
    | sort\
    | sed 's/[^/]*\//|  /g; ;s/| *\([^| ]\)/+-- \1/'
}
alias find-tree=find_tree

# Trim spaces, new lines, comments, empty lines, etc.
alias trim-space='sed -e '\''s/^[ \t]*//; s/[ \t]*$//;'\'''
alias trim-nl='tr -d '\''\n'\'''
alias trim-comments='sed '\''/^#.*$/d'\'''
alias trim-empty='sed '\''/^$/d'\'''
alias trim-noi18n='sed '\''s~[[:space:]]*//[[:space:]]*NOI18N[[:space:]]*~~g'\'''

alias encode-secret="${BASH_PROFILE_DIR}"'/sh/secret.sh'
alias decode-secret="${BASH_PROFILE_DIR}"'/sh/secret.sh -d'

function prompt() {
  eval "$("${BASH_PROFILE_DIR}"/sh/prompt.sh "$@")"
}

function new_sh() {
  [[ ! -e ${1:?filename} ]] && echo '#!/usr/bin/env bash' > "${1}"
}

if command -v cygpath &> /dev/null; then
  # Convert Unix format paths to Windows path, with regular slashes.
  function winpath() {
    cygpath "${1}" --absolute --mixed
  }

  # Convert Windows format paths (with any type of slashes) to Unix path.
  function nixpath() {
    cygpath "${1}" --absolute --unix   
  }

elif [[ -n ${DRIVES_PATH} ]]; then
  # Convert Unix format paths to Windows path, with regular slashes.
  function winpath() {
    local nix_path=$1
    local sed_script="s|^${DRIVES_PATH/%\//}/\([a-zA-Z]\)/|\1:/|"
    local ret
    ret=$(echo "${nix_path}" | sed -e "${sed_script}")
    if [[ ${ret:1:1} = ':' ]]; then
      echo "${ret^}"
    else
      echo "${ret}"
    fi
  }

  # Convert Windows format paths (with any type of slashes) to Unix path.
  function nixpath() {
    local win_path=$1
    local sed_script="s|\\\\|/|g; s|^\([a-zA-Z]\):|${DRIVES_PATH/%\//}/\1|"
    echo "${win_path,}" | sed -e "${sed_script}"
  }
fi

# Current date/time in different formats
function now() {
  case ${1:-d} in
    z) date '+%Y-%m-%dT%H:%M:%SZ' ;; # 2023-10-13T11:06:50Z
    d) date '+%Y-%m-%d %H:%M:%S'  ;; # 2023-10-13 11:09:53
    f) date '+%Y%m%d-%H%M%S'      ;; # 20231013-111012
    *) date '+%s%N'               ;; # 1700402587668480465
  esac
}

# Make directory (or directories) and change the shell working directory
function mkcd() {
  mkdir -p "$1" && cd "$1" || return $?
}

# Go to the first directory where the command executable is found
function cdto() {
  local cmd=${1:?target}

  if [[ -d "${cmd}" ]]; then
    cd "${cmd}" || return 2
    return 0
  fi

  if [[ -f "${cmd}" ]]; then
    cd "$(dirname "${cmd}")" || return 3
    return 0
  fi

  local -a paths
  IFS='' read -r -a paths < <(which "${cmd}" 2> /dev/null)

  if [[ ${#paths[@]} -gt 0 ]]; then
    cd "$(dirname "${paths[0]}")" || return 4
    return 0
  fi

  return 1
}

# Swap the contents of two files
function swap_files() {
  local tmp=tmp.$$
  mv "${1}" ${tmp} && mv "${2}" "${1}" && mv ${tmp} "${2}"
}

# Swap the names of two files
function swap_names() {
  local dir1 name1 dir2 name2

  test $# -eq 2 || return 2

  test -e "${1}" || return 3
  test -e "${2}" || return 3

  dir1=$(dirname "$1"); name1="$(basename "$1")"
  dir2=$(dirname "$2"); name2="$(basename "$2")"

  (cd "${dir1}" && mv -T  "${name1}" ".${name2}") && \
  (cd "${dir2}" && mv -T  "${name2}"  "${name1}") && \
  (cd "${dir1}" && mv -T ".${name2}"  "${name2}")
}

# Make a backup copy of a file
function backup_file() {
  cp -v "${1}" "${1}-$(now f)"
}

# Rename files matching "*${1}*" to "*${2}*"
function rename_all() {
  local match=$1 replace=$2
  for filename in *"${match}"*; do
    mv -v "${filename}" "${filename/${match}/${replace}}"
  done
}

# Print META-INF/MANIFEST.MF of a jar file
function jar_info() {
  local dir
  for jar in "$@"; do
    dir=$(mktemp -d)
    unzip -q "${jar}" -d "${dir}" META-INF/MANIFEST.MF
    mv "${dir}/META-INF/MANIFEST.MF" "${jar}-info"
    rm -rf "${dir}"
    cat "${jar}-info"
  done
}
